### ISSUE TITLE
Cooldown Question/Potential Bug

### ISSUE THREAD

**Issue by mercurialmusic** [MrABCDevelopment/RandomLootChest#12]
Hello! We've been really enjoying this plugin! A question on the chest cooldowns, though -- what is the correct format? We have tried ```Cooldown: 4d``` and ```Cooldown: 345600s``` but 4d seems to default to 24 hours and 345600s seems to remove any cooldown whatsoever. Using other formats like ```Cooldown: 4 days``` results in an error.

We had SQLITE enabled but noticed the database does not have any size to it so assume nothing is being written/saved to it. Will also try MySQL to see if that helps at all. Any advice would be appreciated!

**Comment by MrABCDevelopment** [comment]
Hey, I think it is a bug (but to this day, I haven't noticed anything suspicious), moreover - in the next update, there will be new database system, so all errors should be fixed. Thank you for using RandomLootChest!

**Comment by mercurialmusic** [comment]
Thanks for the quick response! I'll look forward to the next release.

**Comment by mercurialmusic** [comment]
Commenting again on the off chance it's useful to you, I've since experimented with all 3 database types and it seems like data just isn't being saved in any of them. MySQL tables are created but remain empty, same for the database.db for SQLite - it creates the file but it remains at 0 bytes. The YAML option creates the ```users``` directory, but it remains empty. 

Plugin startup seems normal (this one with the SQLite test):
```
[04:31:11] [Server thread/INFO]: [RandomLootChest] Enabling RandomLootChest v1.7.3
[04:31:11] [Server thread/INFO]: You are using v1_20_R1 version.
[04:31:11] [Server thread/INFO]: This version enabled all features!
[04:31:11] [Server thread/INFO]: Loaded 8 items from 'items.yml'!
[04:31:11] [Server thread/INFO]: 10 chests loaded!
[04:31:11] [Server thread/INFO]: Loaded 29 messages
[04:31:11] [Server thread/INFO]: Connecting to database...
[04:31:11] [Server thread/INFO]: Connected to the SQLite database...
[04:31:11] [Server thread/INFO]: Connected to SQLite database.
[04:31:11] [Thread-43/INFO]: Loading data...
[04:31:11] [Thread-43/INFO]: Loaded data!
```

The only errors I was able to extract from any of it was the following on shutdown (SQLite):
```
[04:30:03] [Thread-54/INFO]: Saving data...
[04:30:03] [Server thread/INFO]: Disconnected from the database.
[04:30:03] [Thread-54/WARN]: java.sql.SQLException: database connection closed
[04:30:03] [Thread-54/WARN]: 	at org.sqlite.SQLiteConnection.checkOpen(SQLiteConnection.java:429)
[04:30:03] [Thread-54/WARN]: 	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:31)
[04:30:03] [Thread-54/WARN]: 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:226)
[04:30:03] [Thread-54/WARN]: 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:206)
[04:30:03] [Thread-54/WARN]: 	at RandomLootChest-1.7.3.jar//me.dreamdevs.github.randomlootchest.database.DatabaseSQLite.insertData(DatabaseSQLite.java:120)
[04:30:03] [Thread-54/WARN]: 	at RandomLootChest-1.7.3.jar//me.dreamdevs.github.randomlootchest.database.DatabaseSQLite.saveData(DatabaseSQLite.java:64)
[04:30:03] [Thread-54/WARN]: 	at RandomLootChest-1.7.3.jar//me.dreamdevs.github.randomlootchest.database.Database.lambda$saveData$0(Database.java:40)
[04:30:03] [Thread-54/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[04:30:03] [Thread-54/INFO]: Error has occure while inserting data!
[04:30:03] [Thread-54/INFO]: Something went wrong while saving data!
```

And MySQL shutdown:
```
[04:21:25] [Server thread/INFO]: [RandomLootChest] Disabling RandomLootChest v1.7.3
[04:21:25] [Thread-2271/INFO]: Saving data...
[04:21:25] [Server thread/INFO]: Disconnected from the database.
[04:21:25] [Thread-2271/WARN]: java.sql.SQLNonTransientConnectionException: No operations allowed after connection closed.
[04:21:25] [Thread-2271/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:111)
[04:21:25] [Thread-2271/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:98)
[04:21:25] [Thread-2271/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:90)
[04:21:25] [Thread-2271/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:64)
[04:21:25] [Thread-2271/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:74)
[04:21:25] [Thread-2271/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:73)
[04:21:25] [Thread-2271/WARN]: 	at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1621)
[04:21:25] [Thread-2271/WARN]: 	at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1535)
[04:21:25] [Thread-2271/WARN]: 	at RandomLootChest-1.7.3.jar//me.dreamdevs.github.randomlootchest.database.DatabaseMySQL.insertData(DatabaseMySQL.java:106)
[04:21:25] [Thread-2271/WARN]: 	at RandomLootChest-1.7.3.jar//me.dreamdevs.github.randomlootchest.database.DatabaseMySQL.saveData(DatabaseMySQL.java:50)
[04:21:25] [Thread-2271/WARN]: 	at RandomLootChest-1.7.3.jar//me.dreamdevs.github.randomlootchest.database.Database.lambda$saveData$0(Database.java:40)
[04:21:25] [Thread-2271/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[04:21:25] [Thread-2271/WARN]: Caused by: com.mysql.cj.exceptions.ConnectionIsClosedException: No operations allowed after connection closed.
[04:21:25] [Thread-2271/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[04:21:25] [Thread-2271/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[04:21:25] [Thread-2271/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[04:21:25] [Thread-2271/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[04:21:25] [Thread-2271/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[04:21:25] [Thread-2271/WARN]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
[04:21:25] [Thread-2271/WARN]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[04:21:25] [Thread-2271/WARN]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:150)
[04:21:25] [Thread-2271/WARN]: 	at com.mysql.cj.NativeSession.checkClosed(NativeSession.java:753)
[04:21:25] [Thread-2271/WARN]: 	at com.mysql.cj.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:565)
[04:21:25] [Thread-2271/WARN]: 	at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1550)
[04:21:25] [Thread-2271/WARN]: 	... 5 more
[04:21:25] [Thread-2271/INFO]: Something went wrong while inserting data!
[04:21:25] [Thread-2271/INFO]: Something went wrong while saving data...
```

**Comment by MrABCDevelopment** [comment]
Hey, there's new version of RandomLootChest, if you have any test server, just test it using SQLite or YAML database - if there will be any problem, report it again.

**Comment by mercurialmusic** [comment]
Hey, thanks for the update! Using SQLite on RandomLootChest v1.8.0-BETAv2 with git-Paper-171 I'm now getting the following on startup: https://gist.github.com/mercurialmusic/4d40d4dbb70ea2979b64edd82a066c29 (Note that I removed the individual loading of the chests in case any of my players see this - spoilers!)

And this on data save: https://gist.github.com/mercurialmusic/cfbecca2bba81c4bf938a87f5edb9e69

In game the behavior is the same as before, chests are set to ```Cooldown: 4d```, I am able to access a chest and loot is generated correctly, but when I try to access it again it tells me I can't access the chest for another 23h, 59m etc. rather than the 4d that I'd expect. I tried this on a newly generated SQLite database, which this time at least started up with a 12KB size instead of the previous 0b.

**Comment by MrABCDevelopment** [comment]
I posted an update about 30 minutes ago, let me know if something is not as it should be.

**Comment by mercurialmusic** [comment]
Thanks again! As far as I can tell, still no luck with the database or any change in cooldowns. Using an SQLite explorer it looks like data just isn't being saved in the database. The tables are created, but nothing in them. 

Testing with the YAML database type it does at least now create a file for my player, but it remains empty even after several cycles of the plugin saying it's saving data:
```
UUID: bfa787d5-633b-47b8-a669-2fdbdbecfe91
ActiveCooldown: []
```
In both cases the cooldown shows 24 hours or less (this counts down accurately) until a restart, after which it resets, making me think the cooldown data is remaining in memory but is never actually saved to disk.

That said, it'd still be weird for it to save a 24 hour cooldown to memory when the cooldown is in the config as ```Cooldown: 4d```.

Also a question about the new global cooldown - is the ```personal-cooldown: true``` meant to go in the chest config or the main config?

**Comment by MrABCDevelopment** [comment]
Hey, I'm sorry to hear that nothing has fixed. I'm gonna check that in different situations and conditions, because as far as I tested, I didn't notice nothing wrong, but I keep that in mind.

Option `personal-cooldown` is in config.yml and defines if all players has to have same cooldown per-chest/global cooldown per chest or if they have their own cooldowns.

**Comment by MrABCDevelopment** [comment]
Hey, latest version should fix all problems, including time formatting and database problems. If there are still some problems, let me know creating new issue or by creating ticket on new discord server.
