### ISSUE TITLE
 Issue with "RandomLootChest" plugin during server start and shutdown

### ISSUE THREAD

**Issue by LokeEu** [MrABCDevelopment/RandomLootChest#14]
I am encountering an issue with the "RandomLootChest" plugin (version 1.8.2.2) when I try to shut down my Minecraft server. The plugin seems to throw a NullPointerException related to the extension manager during its disabling process. This error prevents the server from shutting down cleanly.

here error in logs
[02:53:13] [Server thread/ERROR] [Minecraft/]: Error occurred while disabling RandomLootChest vv1.8.2.2 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "me.dreamdevs.randomlootchest.managers.ExtensionManager.disableExtensions()" because the return value of "me.dreamdevs.randomlootchest.RandomLootChestMain.getExtensionManager()" is null
at me.dreamdevs.randomlootchest.RandomLootChestMain.onDisable(RandomLootChestMain.java:129) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[forge:?] {re:classloading}
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:376) ~[forge:?] {re:classloading}
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:501) ~[forge:?] {re:classloading}
at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:493) ~[forge:?] {re:classloading}
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.disablePlugins(CraftServer.java:427) ~[forge:?] {re:classloading}
at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:687) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.server.dedicated.DedicatedServer.func_71260_j(DedicatedServer.java:641) ~[?:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:913) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:286) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at java.lang.Thread.run(Thread.java:831) [?:?] {}
[02:53:13] [Server thread/INFO] [co.sk.wo.bu.WorldEditPlugin/]: [WorldEdit] Disabling WorldEdit v7.2.17+6544-56d0383
[02:53:13] [Server thread/INFO] [co.sk.wo.ex.pl.PlatformManager/]: Unregistering com.sk89q.worldedit.bukkit.BukkitServerInterface from WorldEdit
[02:53:13] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[02:53:13] [Server thread/INFO] [minecraft/ServerPlayNetHandler]: NillySilly lost connection: Server closed
[02:53:13] [Server thread/INFO] [minecraft/DedicatedServer]: NillySilly left the game
[02:53:13] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[02:53:13] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[DayZ]'/minecraft:overworld
[02:53:25] [Server thread/INFO] [minecraft/ChunkManager]: ThreadedAnvilChunkStorage (world): All chunks are saved
[02:53:25] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[DIM-1]'/minecraft:the_nether
[02:53:25] [Server thread/INFO] [minecraft/ChunkManager]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[02:53:25] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[DIM1]'/minecraft:the_end
[02:53:25] [Server thread/INFO] [minecraft/ChunkManager]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[02:53:25] [Server thread/INFO] [minecraft/RConThread]: Thread Query Listener stopped

**Comment by MrABCDevelopment** [comment]
Hey, please show all extensions that you've put to the extensions directory. I think one of them is incompatible due to changes in API.

**Comment by LokeEu** [comment]
i do not have any extensions installed

**Comment by MrABCDevelopment** [comment]
Hey, I've just tested this engine on latest 1.19.3 version and I've got no errors. Are you using legacy version? And yes, you can write in polish.

**Comment by LokeEu** [comment]
uzywam wersji 1.16.5 mam tez mody wgrane ale testowalem to tez bez modow i tak wyskakuje error mg podac liste modow jezeli bedzie trzeba

**Comment by MrABCDevelopment** [comment]
Hey, generally - this engine is not supported (all kind of mods are not supported), so I would recommend to stick around classic spigot, paper, purpur engine. As I mentioned yesterday, I didn't get any error and I tested it without mods, but installed newest RandomLootChest version 1.8.2.2 with 2 extensions.

**Comment by LokeEu** [comment]
ok dzięki za pomoc zancze używać jednego z wymienionych silników jak bd mieć jeszcze jakieś dalsze problemy to tu napisze
