### ISSUE TITLE
No changes in locations.yml

### ISSUE THREAD

**Issue by Rod-bor** [MrABCDevelopment/RandomLootChest#16]
When I create a chest with a wand, loot appears and recovers just as it should. However, when I restart the server, the chests are already empty. In locations.yml does not display the points of adding chests that I install and locations.yml contains only "[]". **I really hope that you will fix this bug, because the plugin is absolutely useless with it, and I have already spent a couple of hours setting up the loot of chests**

Another problem I found is if you run /rlc reload, a menu opens in which 2 buttons don't work - reload config.yml and reload all. But if run /rlc reload chests, the menu is also opening. When you click reload config.yml, the following error is displayed at all:

```
[09:58:02 ERROR]: Could not pass event InventoryClickEvent to RandomLootChest vv1.8.2.2
java.lang.RuntimeException: java.io.FileNotFoundException: config.yml (The specified file cannot be found)
        at me.dreamdevs.randomlootchest.api.Config.reloadFile(Config.java:61) ~[RandomLootChest-v1.8.2.2.jar:?]
        at me.dreamdevs.randomlootchest.menus.ReloadMenu.lambda$new$0(ReloadMenu.java:21) ~[RandomLootChest-v1.8.2.2.jar:?]
        at me.dreamdevs.randomlootchest.api.inventory.buttons.ActionMenuItem.onItemClick(ActionMenuItem.java:20) ~[RandomLootChest-v1.8.2.2.jar:?]
        at me.dreamdevs.randomlootchest.api.inventory.ItemMenu.onInventoryClick(ItemMenu.java:131) ~[RandomLootChest-v1.8.2.2.jar:?]
        at me.dreamdevs.randomlootchest.api.inventory.handlers.ItemMenuListener.onInventoryClick(ItemMenuListener.java:31) ~[RandomLootChest-v1.8.2.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor392.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-167]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-167]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-167]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3258) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-167]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-167]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-167]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1425) ~[paper-1.20.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-167]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.io.FileNotFoundException: config.yml (The specified file cannot be found)
        at java.io.FileInputStream.open0(Native Method) ~[?:?]
        at java.io.FileInputStream.open(FileInputStream.java:216) ~[?:?]
        at java.io.FileInputStream.<init>(FileInputStream.java:157) ~[?:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:126) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:184) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at me.dreamdevs.randomlootchest.api.Config.reloadFile(Config.java:59) ~[RandomLootChest-v1.8.2.2.jar:?]
        ... 28 more

```

**Comment by MrABCDevelopment** [comment]
Hey, I'm sorry that this issue was so long without response - latest update fixed all issues that you mentioned.

Have fun using RandomLootChest, hope you enjoy it.
